### ISSUE TITLE
Bootstrap Carousel  Problem

### ISSUE THREAD

**Issue by omermindivanli** [mndvn/visioncenter.se#4]
In my home.js file - Home component - I have used a bootstrap 4.0.0 aplha version's carousel. I have just used carousel.css and index.html's code copy and paste. but It does not work. Is it stems from jquery? Before I have experienced an incompatibility of version. Some features did not work in Bootstrap. But I have tried everything to fix it. 
The images in Carousel and captions are not responsive. Is there any person have an idea to solve that problem? 
For webpage: 
http://165.227.162.187/

Best Regards....

**Comment by hasanmumin** [comment]
check 
https://getbootstrap.com/docs/4.0/components/carousel/#with-captions

your structure is different than example. 

```
<div class="carousel-item">
  <img src="..." alt="...">
  <div class="carousel-caption d-none d-md-block">
    <h5>...</h5>
    <p>...</p>
  </div>
</div>
```
Your:
```
<div class="carousel-item">
   <img class="third-slide" src="http://x-conshaninge.se/x/wp-content/uploads/2017/04/Boende-slider-3.jpg" alt="Third slide">
   <div class="container">
      <div class="carousel-caption text-right">
         <h1>One more for good measure.</h1>
         <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
         <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
      </div>
   </div>
</div>
```

**Comment by omermindivanli** [comment]
Thanks Hasan, I have solved the problem. The structure was wrong. Now it works. Have a nice weekend..
